name: FloxBx
options:
  bundleIdPrefix: com.brightdigit
settings:
  DEVELOPMENT_TEAM: MLT7M394S7
  CODE_SIGN_IDENTITY: "Apple Development"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
packages:
  FloxBxKit:
    path: ./Packages/FloxBxKit
targets:
  FloxBx.watchkitapp.watchkitextension:
    type: watchkit2-extension
    platform: watchOS
    dependencies:
      - package: FloxBxKit
    sources:
      - path: "Support/watchOS/Extension"
        name: Support
        group: Extension
      - path: "Shared"
    info:
      path: Support/watchOS/Extension/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FloxBx
        NSExtension:
          NSExtensionAttributes:
            WKAppBundleIdentifier: com.brightdigit.FloxBx.watchkitapp
          NSExtensionPointIdentifier: com.apple.watchkit
        WKRunsIndependentlyOfCompanionApp: true
 # settings:
 #   configs:
 #     Debug:
 #       CODE_SIGN_IDENTITY: iPhone Developer
 #       PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.Heartwitch-watchOS-app.watchkitapp.watchkitextension
 #     Release:
 #       CODE_SIGN_IDENTITY: iPhone Distribution
 #       PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.Heartwitch-watchOS-app.watchkitapp.watchkitextension
  FloxBx.watchkitapp:
    type: application.watchapp2
    platform: watchOS
    scheme: {}
    dependencies:
      - target: "FloxBx.watchkitapp.watchkitextension"
    sources:
      - path: "Support/watchOS/Application"
        name: Support
        group: Extension
      - path: "Shared/Assets.xcassets"
    info:
      path: Support/watchOS/Application/Info.plist
      properties:
        WKWatchKitApp: true
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FloxBx
        WKCompanionAppBundleIdentifier: com.brightdigit.FloxBx
#   settings:
#     base:
#       ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
#       PRODUCT_NAME: Heartwitch
#       PRODUCT_MODULE_NAME: Heartwitch_watchOS_app_watchkitapp_watchkitextension
#       IBSC_MODULE: Heartwitch_watchOS_app_watchkitapp_watchkitextension
#     configs:
#       Debug:
#         CODE_SIGN_IDENTITY: iPhone Developer
#         PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.Heartwitch-watchOS-app.watchkitapp
#       Release:
#         CODE_SIGN_IDENTITY: iPhone Distribution
#         PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.Heartwitch-watchOS-app.watchkitapp
  FloxBx:
    type: application
    platform: iOS
    dependencies:
      - package: FloxBxKit
      - target: "FloxBx.watchkitapp"
    sources:
      - path: "Support/iOS"
        name: Support
      - path: "Shared"
    info:
      path: Support/iOS/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FloxBx
#   settings:
#     base:
#       PRODUCT_NAME: Heartwitch
#     configs:
#       Debug:
#         CODE_SIGN_IDENTITY: iPhone Developer
#         PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.Heartwitch-watchOS-app
#       Release:
#         CODE_SIGN_IDENTITY: iPhone Distribution
#         PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.Heartwitch-watchOS-app
